# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: CI

on: [ push, workflow_dispatch ]

jobs:
  build-publish-jar:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    outputs:
      outputGetVersion: ${{ steps.stepGetVersion.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Maven Setting
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.USER_PACKAGE_READ }}",
                "password": "${{ secrets.TOKEN_PACKAGE_READ }}"
            }]

      - name: Get Version
        id: stepGetVersion
        run: |
          IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$IMAGE_TAG"

      - name: Check if version already exists
        run: |
          ! mvn --batch-mode dependency:get -DskipTests -Dmaven.main.skip -Dartifact=io.moost.rp:${{ github.event.repository.name }}:${{ steps.stepGetVersion.outputs.version }}

      - name: Build with Maven
        env:
          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
        run: mvn --batch-mode --update-snapshots verify

      - name: Publish Package
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn -B deploy -DskipTests -Dmaven.main.skip

  cleanup-old-package-versions:
    needs: build-publish-jar
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Cleanup old Package Versions
        uses: actions/delete-package-versions@v3
        with:
          min-versions-to-keep: 5
          package-name: "io.moost.rp.${{ github.event.repository.name }}"
